### ISSUE TITLE
Data Acquisition

### ISSUE THREAD

**Issue by wpowell31** [wpowell31/biostats-821-final-project#1]
# Issue 1: Data Acquisition

Goal: Collect data for training and testing the NBA game prediction model using API
Assignee: Nick
Description:
Identify and obtain relevant datasets for NBA games such as player stats, team stats, and game schedules from reputable sources
Clean and preprocess the data to remove any errors or inconsistencies
Transform the data into a format suitable for training the PyTorch model

**Comment by patrickkwang** [comment]
Please ensure that this data collection is a repeatable process. That is, the deliverable for this step should not be the data itself, but rather the code and documentation for generating it.

**Comment by nickb1125** [comment]
data steps complete
