### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by wpowell31** [wpowell31/biostats-821-final-project#3]
# Issue 3: Command Line Interface

Goal: Create a user-friendly command line interface that allows users to interact with the NBA game prediction application
Assignee: Wanying
Description:
Design and implement a command line interface that accepts user input such as team names and dates
Integrate the PyTorch model developed by Person B to predict the outcome of NBA games based on user input
Display the predicted outcomes to the user in a clear and understandable format

**Comment by patrickkwang** [comment]
There is also a Flask API discussed in the README. Do you plan to build both?

**Comment by nickb1125** [comment]
cli complete
